version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
