version: '3.8'
services:
  app:
    build:
      context: C:\Users\anish\tanX_AG
      dockerfile: C:\Users\anish\tanX_AG\Dockerfile
    volumes:
      - C:\Users\anish\tanX_AG:/app
    command: python app.py

  test:
    build:
      context: C:\Users\anish\tanX_AG
      dockerfile: C:\Users\anish\tanX_AG\Dockerfile.test
    volumes:
      - C:\Users\anish\tanX_AG:/app
    command: pytest tests
